const { pool } = require("../config/database");

// AI Advisor - Context-aware AI governance chatbot for Indian regulations
// Uses a knowledge base approach with Indian regulatory context

const KNOWLEDGE_BASE = {
  dpdp: {
    keywords: ["dpdp", "data protection", "personal data", "consent", "data principal", "data fiduciary", "data breach notification", "cross-border", "children data"],
    responses: {
      general: "The Digital Personal Data Protection Act (DPDP) 2023 is India's comprehensive data protection law. Key requirements include: obtaining informed consent, providing clear notices, enabling data principal rights, implementing data breach notification within 72 hours, and ensuring cross-border transfer compliance.",
      consent: "Under DPDP 2023, consent must be free, specific, informed, unconditional, and unambiguous. You must provide a clear notice before collecting consent. Data Principals can withdraw consent at any time. For children's data (under 18), verifiable parental consent is mandatory.",
      breach: "Under DPDP 2023, personal data breaches must be notified to the Data Protection Board of India and affected Data Principals. The notification must describe the nature of the breach, potential consequences, and measures taken.",
      rights: "Data Principals have the right to: (1) Access information about processing, (2) Correction and erasure of data, (3) Grievance redressal, (4) Nominate another person to exercise rights in case of death/incapacity.",
      fiduciary: "Data Fiduciary obligations include: ensuring data accuracy, implementing security safeguards, deleting data when purpose is fulfilled, conducting DPIAs if classified as Significant Data Fiduciary, and appointing a DPO.",
      cross_border: "Cross-border data transfer is permitted except to countries specifically restricted by the Central Government. Maintain records of all cross-border transfers and ensure adequate protection in recipient jurisdictions.",
      children: "Processing children's data (under 18) requires verifiable parental consent. Tracking, behavioral monitoring, and targeted advertising directed at children is prohibited.",
    },
  },
  niti_aayog: {
    keywords: ["niti aayog", "responsible ai", "rai", "ethics", "fairness", "transparency", "accountability"],
    responses: {
      general: "NITI Aayog's Responsible AI (RAI) principles focus on 7 key areas: Safety & Reliability, Equality & Inclusivity, Transparency & Explainability, Privacy & Security, Accountability, Protection of Positive Human Values, and Non-maleficence.",
      fairness: "Ensure AI systems do not discriminate based on caste, religion, gender, language, or region. Conduct regular bias audits, especially for systems serving India's diverse population. Use representative datasets that include underrepresented communities.",
      transparency: "Implement explainability methods appropriate to the risk level. High-risk AI systems should provide clear explanations in languages understood by affected users, including regional Indian languages where applicable.",
    },
  },
  meity: {
    keywords: ["meity", "ministry", "advisory", "ai advisory", "labeling", "government approval"],
    responses: {
      general: "MeitY's 2024 AI Advisory requires: (1) Clear labeling of AI-generated content, (2) Bias testing before deployment, (3) Government approval for untested/unreliable AI, (4) Robust content moderation, (5) User consent for AI interactions, (6) Grievance officer appointment.",
      labeling: "All AI-generated content must be clearly labeled to prevent misinformation. This includes text, images, audio, and video generated by AI systems.",
      approval: "AI platforms deploying under-tested or unreliable AI must seek explicit government permission before making such models available to Indian users.",
    },
  },
  cert_in: {
    keywords: ["cert-in", "certin", "incident", "reporting", "6 hour", "cyber security", "breach"],
    responses: {
      general: "CERT-In requires reporting of cyber security incidents within 6 hours. Key requirements: (1) Maintain logs for 180 days, (2) Designate 24x7 point of contact, (3) Synchronize system clocks with NTP, (4) Report incidents including data breaches, unauthorized access, and AI system compromises.",
      reporting: "The 6-hour reporting window starts from the time you become aware of the incident. Report via the CERT-In portal or email. Include: nature of incident, systems affected, impact assessment, and remediation steps taken.",
      logs: "All ICT system logs must be maintained for a rolling 180-day period within Indian jurisdiction. This includes AI model inference logs, access logs, and system event logs.",
    },
  },
  rbi: {
    keywords: ["rbi", "reserve bank", "banking", "financial", "lending", "credit", "fintech"],
    responses: {
      general: "RBI guidelines for AI/ML in financial services require: model governance framework, fairness in lending decisions, independent model validation, customer explanations for AI decisions, complete audit trails, and board-level oversight.",
      lending: "AI/ML models used in credit decisions must not discriminate based on caste, religion, gender, or other protected characteristics under the Constitution of India. Regular fairness audits are mandatory.",
      validation: "All AI/ML models must undergo independent validation before deployment and periodic re-validation. Document model performance, drift monitoring, and any retraining activities.",
    },
  },
  sebi: {
    keywords: ["sebi", "securities", "trading", "algorithm", "market"],
    responses: {
      general: "SEBI requires disclosure of algorithmic trading and AI-based advisory systems, implementation of risk controls, prevention of market manipulation, and investor protection measures.",
    },
  },
  irdai: {
    keywords: ["irdai", "insurance", "underwriting", "claims"],
    responses: {
      general: "IRDAI guidelines require fairness in AI-based underwriting, transparency in claims processing, explicit consent for personal data use, and comprehensive model documentation.",
    },
  },
  risk_assessment: {
    keywords: ["risk", "assessment", "classify", "classification", "high risk", "minimal risk"],
    responses: {
      general: "AI Risk Classification in the Indian context: (1) Unacceptable Risk - AI that manipulates human behavior or exploits vulnerabilities, (2) High Risk - AI in healthcare, finance, law enforcement, education, (3) Limited Risk - AI with transparency obligations, (4) Minimal Risk - Low-impact AI applications.",
      high_risk: "High-risk AI systems in India include: AI in banking/lending decisions, healthcare diagnostics, judicial/legal processes, employment screening, educational assessments, and critical infrastructure. These require enhanced governance, regular auditing, and human oversight.",
    },
  },
  compliance: {
    keywords: ["compliance", "how to comply", "getting started", "steps", "checklist"],
    responses: {
      general: "Getting started with AI governance compliance in India:\n1. Map all AI systems in your organization\n2. Classify each by risk level\n3. Identify applicable frameworks (DPDP, sector-specific)\n4. Conduct gap assessment against each framework\n5. Implement required controls and policies\n6. Document evidence of compliance\n7. Set up incident reporting procedures\n8. Schedule periodic reviews and audits\n9. Train your team on AI governance\n10. Establish ongoing monitoring",
    },
  },
};

const processAdvisorQuery = async (query, sessionId, userId, organizationId) => {
  const lowerQuery = query.toLowerCase();

  // Find best matching knowledge area
  let bestMatch = null;
  let bestScore = 0;

  for (const [area, data] of Object.entries(KNOWLEDGE_BASE)) {
    let score = 0;
    for (const keyword of data.keywords) {
      if (lowerQuery.includes(keyword)) {
        score += keyword.length; // longer keyword matches = higher confidence
      }
    }
    if (score > bestScore) {
      bestScore = score;
      bestMatch = area;
    }
  }

  let response;

  if (bestMatch && bestScore > 0) {
    const area = KNOWLEDGE_BASE[bestMatch];
    // Find best sub-topic
    let subTopic = "general";
    if (area.responses) {
      for (const [topic, _] of Object.entries(area.responses)) {
        if (topic !== "general" && lowerQuery.includes(topic.replace("_", " "))) {
          subTopic = topic;
          break;
        }
      }
    }
    response = area.responses[subTopic] || area.responses.general;
  } else {
    response = `I can help you with AI governance questions related to Indian regulations. Try asking about:\n\n• **DPDP Act 2023** - Data protection, consent, breach notification\n• **NITI Aayog RAI** - Responsible AI principles, fairness, transparency\n• **MeitY Guidelines** - AI platform regulation, content labeling\n• **CERT-In** - Incident reporting (6-hour window), log retention\n• **RBI AI/ML** - Financial services AI governance\n• **SEBI AI** - Securities market AI disclosure\n• **IRDAI AI** - Insurance AI guidelines\n• **Risk Assessment** - AI risk classification for India\n• **Compliance** - Getting started with AI governance\n\nWhat would you like to know?`;
  }

  // Save chat history
  await pool.query(
    `INSERT INTO ai_advisor_chats (user_id, organization_id, session_id, role, content)
     VALUES ($1, $2, $3, 'user', $4)`,
    [userId, organizationId, sessionId, query]
  );

  await pool.query(
    `INSERT INTO ai_advisor_chats (user_id, organization_id, session_id, role, content)
     VALUES ($1, $2, $3, 'assistant', $4)`,
    [userId, organizationId, sessionId, response]
  );

  return response;
};

const getChatHistory = async (sessionId, limit = 50) => {
  const result = await pool.query(
    "SELECT role, content, created_at FROM ai_advisor_chats WHERE session_id = $1 ORDER BY created_at ASC LIMIT $2",
    [sessionId, limit]
  );
  return result.rows;
};

module.exports = { processAdvisorQuery, getChatHistory };
